from __future__ import annotations

from cubie.settings.store import (
    EXTERNAL_VRAM_WAIT_TIMEOUT_SECONDS_KEY,
    GPU_DISABLED_DEVICES_KEY,
    INTERNAL_VRAM_WAIT_TIMEOUT_SECONDS_KEY,
    MAX_LOADED_MODELS_KEY,
    MAX_TASKS_PER_SLOT_KEY,
    SettingsStore,
)

__all__ = (
    "EXTERNAL_VRAM_WAIT_TIMEOUT_SECONDS_KEY",
    "GPU_DISABLED_DEVICES_KEY",
    "INTERNAL_VRAM_WAIT_TIMEOUT_SECONDS_KEY",
    "MAX_LOADED_MODELS_KEY",
    "MAX_TASKS_PER_SLOT_KEY",
    "SettingsStore",
)
